refactor: test functionality changed
bridge-design/website pull request #28
Opened 2023-05-21 23:15 UTC by alexandra-stepanova

2023-05-25 07:28 UTC, varya requested changes
![2023-05-25_10-26-25](https://github.com/bridge-design/website/assets/27215/e7c4ad51-0688-44ee-85dc-56ec8aacb2be)

One requirement doesn't work for me. I have checked Colors and that checked me all the subparts (this is correct). But then I started to uncheck the subparts manually. I expected that when I uncheck the last in the group, it will automatically uncheck the "Colors". But that didn't happen.

2023-06-06 21:26 UTC, alexandra-stepanova commented
@varya Implemented functionality where title property unchecked if all "parts" values are unchecked manually.

2023-06-13 05:39 UTC, varya requested changes
![2023-06-13_08-36-18](https://github.com/bridge-design/website/assets/27215/95fd60a4-442c-4ad1-9b0c-3a8dad00a684)

One more improvement is needed. If I selected ALL the sub categories, its parent also has to be selected. This is not very important, but "nice to have". So try to dedicate it sometime and see if you manage to code it this way. If you don't manage, we can merge as it is and improve later. We need to get it merged somewhen this week so that I can write a blog post about the exercise. Because of that I am offering the "timebox" approach.

2023-06-13 06:51 UTC, alexandra-stepanova commented
@varya got it!

2023-06-13 20:46 UTC, alexandra-stepanova commented
@varya done

2023-06-15 06:27 UTC, merged